# Generated by Django 4.2.6 on 2023-10-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chice',
            new_name='Choice',
        ),
    ]
